library(KoNLP)
# remove.packages("rJava")
# install.packages("rJava")
# library(xlsx)
library(dplyr)
library(stringr)
library(wordcloud2)
library(tm)
buildDictionary(ext_dic = "woorimalsam")

rl <- readLines("review.txt", encoding = "euc-kr")
rl <- gsub("'","",rl)
rl <- gsub("‘","",rl)
rl <- gsub("“","",rl)
rl <- gsub("”","",rl)
rl <- gsub('[ㄱ-ㅎ]','',rl)
rl <- gsub('(ㅜ|ㅠ)+','',rl)
rl <- gsub('[~!@#$%^&*()_+=?]<>','',rl)
rl <- gsub("\\d+","",rl)
rl <- gsub("\\n","",rl)
rl <- gsub("\\.","",rl)
rl <- gsub("\n","",rl)
rl <- gsub("-","",rl)
rl <- gsub("영화","",rl)
rl <- gsub("한","",rl)
rl <- gsub("말","",rl)
rl <- gsub("것","",rl)
rl <- gsub("번","",rl)
rl <- gsub("내","",rl)
rl <- gsub("점","",rl)
rl <- gsub("때","",rl)
rl <- gsub("화","",rl)
rl <- gsub("적","",rl)
rl <- gsub("중","",rl)
rl <- gsub("이","",rl)
rl <- gsub("이영","",rl)
rl <- gsub("몇","",rl)
rl <- gsub("년","",rl)
rl <- gsub("수","",rl)

rll <- lapply(rl, extractNoun)

rll <- gsub("를","",rll)
rll <- gsub("나","",rll)
rll <- gsub("런","",rll)
rll <- gsub("제","",rll)
rll <- gsub("을","",rll)
rll <- gsub("만","",rll)
rll <- gsub("것","",rll)
rll <- gsub("볼","",rll)
rll <- gsub("위","",rll)
rll <- gsub("들","",rll)
rll <- gsub("라","",rll)
rlf <- Filter(function(x) ( nchar(x) <= 7 & nchar(x) >= 2),rll)

rlu <- unlist(rlf)
sw <- sort(table(rlu), decreasing = T)
head(sw,30)
wordcloud2(sw)




