library(KoNLP)
# remove.packages("rJava")
# install.packages("rJava")
library(xlsx)
library(dplyr)
library(stringr)
library(wordcloud2)
library(tm)
buildDictionary(ext_dic = "woorimalsam")

rl <- readLines("review.txt", encoding = "euc-kr")
rl <- gsub("'","",rl)
rl <- gsub("‘","",rl)
rl <- gsub("“","",rl)
rl <- gsub("”","",rl)
rl <- gsub('[ㄱ-ㅎ]','',rl)
rl <- gsub('(ㅜ|ㅠ)+','',rl)
rl <- gsub('[~!@#$%^&*()_+=?]<>','',rl)
rl <- gsub("\\d+","",rl)
rl <- gsub("\\n","",rl)
rl <- gsub("\\.","",rl)
rl <- gsub("\n","",rl)
rl <- gsub("-","",rl)
rl <- gsub("영화","",rl)
rl <- gsub("한","",rl)
rl <- gsub("말","",rl)
rl <- gsub("것","",rl)
rl <- gsub("번","",rl)
rl <- gsub("내","",rl)
rl <- gsub("점","",rl)
rl <- gsub("때","",rl)
rl <- gsub("화","",rl)
rl <- gsub("적","",rl)
rl <- gsub("중","",rl)
rl <- gsub("이","",rl)
rl <- gsub("이영","",rl)
rl <- gsub("몇","",rl)
rl <- gsub("년","",rl)

rle <- lapply(rl, extractNoun)
rlf <- Filter(function(x) ( nchar(x) <= 7 & nchar(x) >= 2 ),rle)

rlu <- unlist(rlf)
sw <- sort(table(rlu), decreasing = T)
wordc <- table(sw, decresing=T)
head(sw)
wordcloud2(sw)

