---
title: "류경민"
output: html_document
---

```{r }
library(dplyr)
library(rvest)
library(stringr)
library(tm)
library(ggplot2)
library(KoNLP)
library(showtext)
library(RColorBrewer)
library(extrafont)
library(nycflights13)
library(tidyverse)
library(lubridate)
library(wordcloud2)
windowsFonts(goB= windowsFont("고도 B"))

```

## 크롤링 코드

```{r}
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

url_base <- 'https://movie.naver.com'
start_url <- '/movie/bi/mi/point.nhn?code=17421'
url <- paste0(url_base, start_url)
html <- read_html(url)
html %>%
  html_node('iframe.ifr') %>%
  html_attr('src') -> if_url
ifr_url <- paste0(url_base, if_url) 
html2 <- read_html(ifr_url)

html2 %>%
  html_node('div.score_total') %>%
  html_nodes('em') -> ems
pages <- ems[2] %>% html_text()
pages <- gsub(",", "", pages)
total_page <- ceiling(as.numeric(pages)/10)

html2 %>%
  html_node('div.paging') %>%
  html_node('a') %>%
  html_attr('href') -> tmp
page_url_base <- str_sub(tmp, 1, -2)

df_points <- data.frame(score=c(), review=c(), writer=c(), time=c())

for (i in 1:total_page) {
  if (i %% 100 == 0)
    print(i)
  page_url <- paste0(url_base, page_url_base, i)
  html <- read_html(page_url)
  html %>%
    html_node('div.score_result') %>%
    html_nodes('li') -> lis
  
  score <- c()
  review <- c()
  writer <- c()
  time <- c()
  for (li in lis) {
    score <- c(score, html_node(li, '.star_score') %>% html_text('em') %>% trim())
    li %>%
      html_node('.score_reple') %>%
      html_text('p') %>%
      trim() -> tmp
    idx <- str_locate(tmp, "\r")
    rev <- str_sub(tmp, 1, idx[1]-1)
    #print(rev)
    review <- c(review, rev)
    tmp <- trim(str_sub(tmp, idx[1], -1))
    idx <- str_locate(tmp, "\r")
    writer <- c(writer, str_sub(tmp, 1, idx[1]-1))
    tmp <- trim(str_sub(tmp, idx[1], -1))
    idx <- str_locate(tmp, "\r")
    time <- c(time, str_sub(tmp, 1, idx[1]-1))
  }
  points <- data.frame(score=score, review=review, writer=writer, time=time)
  df_points <- rbind.data.frame(df_points, points)
}
write.csv(df_points, file="D:/Workspace/R_Project/crawling/cine.xlsx", 
           col.names=TRUE, row.names=FALSE, append=FALSE)
```

## wordcloud 코드
```{r }
buildDictionary(ext_dic = "woorimalsam")
setwd("D:/Workspace/R_Project/crawling_pro")

rl <- readLines("review.txt", encoding = "euc-kr")
rl <- gsub("'","",rl)
rl <- gsub("‘","",rl)
rl <- gsub("“","",rl)
rl <- gsub("”","",rl)
rl <- gsub('[ㄱ-ㅎ]','',rl)
rl <- gsub('(ㅜ|ㅠ)+','',rl)
rl <- gsub('[~!@#$%^&*()_+=?]<>','',rl)
rl <- gsub("\\d+","",rl)
rl <- gsub("\\n","",rl)
rl <- gsub("\\.","",rl)
rl <- gsub("\n","",rl)
rl <- gsub("-","",rl)


rll <- lapply(rl, extractNoun)
head(rll)

gsub_txt <- readLines("c_gsub.txt")
cnt_txt <- length(gsub_txt)

for (i in 1:cnt_txt) {
  rll <- gsub((gsub_txt[i]),"",rll)
}

rlf <- Filter(function(x) ( nchar(x) <= 7 & nchar(x) >= 2),rll)

rlu <- unlist(rlf)
sw <- sort(table(rlf), decreasing = T)
head(sw,30)
wordcloud2(sw)
```



## 전체 시간 그래프
```{r}
data <- read.csv("cine.csv", encoding = "euc-kr")
head(data)

sts <- data %>%
  select(time,score)

rep <- replace(sts, sts=="#N/A",NA)

sto <- na.omit(rep)
sum(is.na(sto))

x <- ymd_hm(sto$time)
score <- sto$score

Year=year(x);Month=month(x);Day=mday(x); Week=wday(x); Hour=hour(x); Minute=minute(x)  
da <- cbind(Year,Month,Day,Hour,Week,score)
dad <- as.data.frame(da)
head(dad)

da1 <- dad %>%
  select(Hour, score) %>%
  group_by(Hour) %>%
  summarise(mean = mean(score))


ggplot(da1, aes(x=Hour,y=mean)) +
  geom_line(size=2,aes(colour = Hour)) +
  theme_bw(base_family = "goB", base_size = 7) +
  geom_text(aes(label=sprintf("%.2f",mean)),size=4,hjust=1,vjust=0,check_overlap = T) +
  geom_line(linetype = "dashed") + ggtitle("시간대별 평균 평점 비교") + 
  labs(x="시간대", y="평점") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=90, size=10)) 
```


## 시간대별 dplyr
```{r}
head(dad)
da2 <- dad %>%
  filter(Year == "2003" | Year=="2004" | Year=="2005"| Year=="2006"| Year=="2007"| Year=="2008") %>%
  select(Hour, score) %>%
  group_by(Hour) %>%
  summarise(mean = mean(score))

da3 <- dad %>%
  filter(Year == "2008" | Year=="2008" | Year=="2010" | Year=="2011" | Year=="2012" | Year=="2013") %>%
  select(Hour, score) %>%
  group_by(Hour) %>%
  summarise(mean = mean(score))

da4 <- dad %>%
  filter(Year == "2013" | Year=="2014" | Year=="2015" | Year=="2016" | Year=="2017") %>%
  select(Hour, score) %>%
  group_by(Hour) %>%
  summarise(mean = mean(score))

da5 <- dad %>%
  filter(Year == "2017" | Year=="2018" | Year=="2019") %>%
  select(Hour, score) %>%
  group_by(Hour) %>%
  summarise(mean = mean(score))
```



## 임기별 평균과 비교 그래프 
```{r}
ggplot(da1, aes(x=Hour,y=mean)) +
  geom_line(size=1,col="black") + 
  geom_line(data=da2, aes(x=Hour,y=mean), col = "chartreuse",size=1) +
  scale_colour_discrete(labels=c("노대통령", "평균")) +
  ggtitle("평균과 비교(노대통령)") + 
  labs(x="시간대", y="평점") +
  geom_hline(yintercept = 9.41,size=2, linetype='dashed',color="orange") +
  annotate("text", x=3, y=9.43, size=4, colour="red", label="평균 = 9.41") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=90, size=10))

ggplot(da1, aes(x=Hour,y=mean)) +
  geom_line(size=1,col="black") + 
  geom_line(data=da3, aes(x=Hour,y=mean), col = "firebrick",size=1) +
  scale_colour_discrete(labels=c("이대통령", "평균")) +
  ggtitle("평균과 비교(이대통령)") + 
  labs(x="시간대", y="평점") +
  geom_hline(yintercept = 9.41, size=2 ,linetype='dashed',color="orange") +
  annotate("text", x=2.8, y=9.38, size=4, colour="red", label="평균 = 9.41") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=90, size=10))

ggplot(da1, aes(x=Hour,y=mean)) +
  geom_line(size=1,col="black") + 
  geom_line(data=da4, aes(x=Hour,y=mean), col = "firebrick4",size=1) +
  scale_colour_discrete(labels=c("박대통령", "평균")) +
  ggtitle("평균과 비교(박대통령)") + 
  labs(x="시간대", y="평점") +
  geom_hline(yintercept = 9.41,size=2, linetype='dashed',color="orange") +
  annotate("text", x=3, y=9.38, size=4, colour="red", label="평균 = 9.41") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=90, size=10))


ggplot(da1, aes(x=Hour,y=mean)) +
  geom_line(size=1,col="black") + 
  geom_line(data=da5, aes(x=Hour,y=mean), col = "royalblue",size=1) +
  scale_colour_discrete(labels=c("문대통령~현재", "평균")) +
  ggtitle("평균과 비교(문대통령~현재)") + 
  labs(x="시간대", y="평점") +
  geom_hline(yintercept = 9.41, size=2,linetype='dashed',color="orange") +
  annotate("text", x=3, y=9.43, size=4, colour="red", label="평균 = 9.41") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=90, size=10))
```

## 임기별 평균 값과의 비교 그래프

```{r}

options(digits = 2)
m1 <- mean(da1$mean)
m2 <- mean(da2$mean)
m3 <- mean(da3$mean)
m4 <- mean(da4$mean)
m5 <- mean(da5$mean)

x1 <- c(m1,m2,m3,m4,m5)
x2 <- c("평균","노","이","박","문")
x3 <- c(1,2,3,4,5)

mdat <- data.frame(x1,x2,x3)
colnames(mdat) <- c("mean", "term","order")
mdat 

ggplot(mdat, aes(x=reorder(term,order), y=mean,fill=term)) + geom_col() +
  coord_cartesian(ylim=c(9,9.8)) +
  ggtitle("시간대별 평균 비교") + 
  labs(x="시간대", y="평점") +
  geom_text(aes(label=round(mean,2)),col="black",vjust=-0.1,size=5) +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(family="goB",size=13),
        axis.title.y=element_text(family="goB",angle=0),
        axis.text.x=element_text(family="goB",angle=0, size=10))

```



## 월별 평점 평균 변화 
```{r}
mod <- dad %>% 
  select(Year, Month) %>% 
  mutate(time = make_datetime(Year, Month))
head(mod)

score <- sto$score
time <- mod$time

mod0 <- data.frame(time, score)

mod00 <- mod0 %>%
  group_by(time) %>%
  summarise(mean = mean(score))
head(mod00)

ggplot(data = mod00, aes(x=time, y=mean)) + geom_line(size=0.5, col="red") + 
  ggtitle("월별 평점 평균 변화") + 
  labs(x="시간대", y="평점") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=0, size=10)) 


```


## 2012-14년도의 평균 변화
```{r}

mod12_14 <- dad %>%
  filter(Year=="2012" | Year=="2013" | Year == "2014") %>%
  select(Year, Month, score) %>%
  mutate(time = make_datetime(Year, Month)) %>%
  select(time, score)

m_mod12_14 <- mod12_14 %>%
  group_by(time) %>%
  summarise(mean = mean(score))


ggplot(data = m_mod12_14, aes(x=time, y=mean)) + geom_line(size=0.5, col="red") + 
  ggtitle("12-14년도 기간동안 월별 평점 평균 변화") + 
  labs(x="시간대", y="평점") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=0, size=10)) 

```



## 13년도 안에서의 평균 변화 
```{r}
mod13 <- dad %>%
  filter(Year=="2013") %>%
  select(Year, Month, score) %>%
  mutate(time = make_datetime(Year, Month)) %>%
  select(time, score)

m_mod13 <- mod13 %>%
  group_by(time) %>%
  summarise(mean = mean(score))


ggplot(data = m_mod13, aes(x=time, y=mean)) + geom_line(size=0.5, col="red") + 
  ggtitle("13년도 기간동안 월별 평점 평균 변화") + 
  labs(x="시간대", y="평점") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=13),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=0, size=10)) 

```


## 요일별 평균 변화
```{r}
wd <- dad %>%
  select(Week, score) %>%
  group_by(Week) %>%
  summarise(mean = mean(score))
wd$Week <- recode(wd$Week,"일","월","화","수","목","금","토")
order <- c(1:7)
options(digits = 2)
wdo <- data.frame(wd,order)


ggplot(data = wdo, aes(x=reorder(Week,order),y=mean,fill=Week)) + geom_bar(stat='identity') + 
  coord_cartesian(ylim=c(9,9.8)) +
  scale_fill_discrete(limits=c("일","월","화","수","목","금","토")) +
  geom_text(aes(label=round(mean,2)),col="black",vjust=-0.1,size=5) +
  ggtitle("요일별 평점 평균 변화") + 
  labs(x="시간대", y="평점") +
  theme(plot.title=element_text(family="goB", face="bold",size=17, color='royalblue'),
        axis.title=element_text(size=17),
        axis.title.y=element_text(angle=0),
        axis.text.x=element_text(angle=0, size=18)) 
```
